name: Automate Weather Data Collection      # name

on:                                         # some event happening
  schedule:                                 # one of the events is on schedule
    - cron: '0 10 * * *'                    # Run daily at 10:00 am (UTC time)  0 minutes  10 hour 10  wildcard * every day every month every year
  workflow_dispatch:                        # Allow manual triggering of the workflow. Ian added this in

jobs:
  run-weather-script:
    runs-on: ubuntu-latest                  # latest version of ubuntu linux. In Cloud environments. Most used operating system. 

    steps:                                  # steps that this job has
      - name: Checkout repository           # Step 1: Checkout the repository
        uses: actions/checkout@v4           # a github action script        https://github.com/actions/checkout    

      - name: Set up shell environment      # Step 2: Set up shell environment
        run: |
          chmod +x weather.sh

       - name: Run weather script           # Step 3: Run the weather.sh script
        run: ./weather.sh

      - name: Configure Git                 # Step 4: Configure Git with your details
        run: |
          git config --global user.name "YourGitHubUsername"
          git config --global user.email "your-email@example.com"

      - name: Commit and push updates                               # Step 5: Commit and push changes
        run: |
          git add .
          git commit -m "Automated weather data update"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


