name: Automate Weather Script

on:
  schedule:
    # Run daily at 10 AM
    - cron: '0 10 * * *'
  workflow_dispatch: # Enable manual triggers
    inputs: {}

permissions:
  contents: write

jobs:
  run-weather-script:
    runs-on: ubuntu-latest # Use the latest version of Linux (Ubuntu) virtual machine

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Run the weather.sh script ensuring the script is executable
    - name: Execute weather.sh
      run: |
        chmod +x weather.sh 
        ./weather.sh

    # Commit and push the changes
    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Automated update from weather.sh"
        git push
